### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by saarao** [axlape/axlape.github.io#2]
Ett rönnbär kanske

**Comment by saarao** [comment]
Favicon rönnlööv


![android-chrome-192x192](https://cloud.githubusercontent.com/assets/25256817/22174204/70180b40-dfe1-11e6-9739-6feecaa5e30c.png)
![android-chrome-512x512](https://cloud.githubusercontent.com/assets/25256817/22174205/7037ad10-dfe1-11e6-83e5-f5ec74b170c5.png)
![apple-touch-icon](https://cloud.githubusercontent.com/assets/25256817/22174206/704985e4-dfe1-11e6-9dcb-d9d89791d949.png)

![favicon-16x16](https://cloud.githubusercontent.com/assets/25256817/22174207/7051fd32-dfe1-11e6-9f4d-aeca77e3f656.png)
![favicon-32x32](https://cloud.githubusercontent.com/assets/25256817/22174208/70554794-dfe1-11e6-9e4d-7974e09c5fc5.png)


![mstile-150x150](https://cloud.githubusercontent.com/assets/25256817/22174209/706a162e-dfe1-11e6-8c6f-37141b909d58.png)



<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">

**Comment by axlape** [comment]
Snygga grejer.  Måst kolla hur de ser ut i miniatyr. Kan bli svårt o få detaljer då man har få pixlar o jobba med.

**Comment by saarao** [comment]
Ser helt bra ut nu tycker ja. Om man e riktigt pet-perfektionist kunde man ta bort några lövrader för att göra den tydligare, men funkar riktigt bra såhä sku ja säg :)

**Comment by axlape** [comment]
Jep,  rikti snyggt då jag kolla favikon i mobil chrome iallafall :) On Jan 30, 2017 6:35 PM, saarao <notifications@github.com> wrote:Ser helt bra ut nu tycker ja. Om man e riktigt pet-perfektionist kunde man ta bort några lövrader för att göra den tydligare, men funkar riktigt bra såhä sku ja säg :)

**Comment by saarao** [comment]
Jo! Nu dessutom fixades äntligen Googlesökningen också!
