### ISSUE TITLE
Rantalinna bild för stor

### ISSUE THREAD

**Issue by axlape** [axlape/axlape.github.io#8]
Rantalinna11 jpg:n över fiskarstranden är 4,5MB. Orimligt stor för alla att ladda ner, speciellt på telefon.

**Comment by saarao** [comment]
Ska förminska! Laddar upp en minilinna

**Comment by saarao** [comment]
![rantalinna-massage-vasa-hieronta-vaasa](https://cloud.githubusercontent.com/assets/25256817/22419464/ebca88f0-e6dd-11e6-9601-1d086cef6b53.jpg)

Nu 72dpi med dimensionen 2800x1855 pixlar (626 kb totalt), vet dock ej om det kommer se bra ut, måst testa. Så smätta jag in lite keywords mesamma, SEO  jejee 

(= Saara Elina Oinonen)

**Comment by saarao** [comment]
I CSS-filen är det fortfarande den stora bilden i bruk. 

#slide1{
    width: 100%;
    background:url('rantalinna11.jpg') 50% 0 no-repeat fixed;

Borde vara denna ovan istället (626kb) med filnamnet rantalinna-massage-vasa-hieronta-vaasa.jpg

Är det bara att ersätta det gamla filnamnet med nya?
